base_model: pretrained_models/Spark-TTS-0.5B/LLM
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

trust_remote_code: true

strict: false

datasets:
  - path: json
    data_files: ["training_data/kazakh_enhanced_v3.jsonl"]
    type: completion
    
dataset_prepared_path:
val_set_size: 0.01
output_dir: ./outputs/out


sequence_len: 2048
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 2
num_epochs: 5
max_steps: 25000
eval_steps: 500
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 1e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 50
xformers_attention:
flash_attention: true

warmup_steps: 10
save_steps: 500
debug:
deepspeed:
weight_decay: 0.0
